In [ ]:
import numpy as np
import pandas as pd

In [ ]:
path_titanic = '/content/drive/MyDrive/machine learning/tested.csv'

In [ ]:
df = pd.read_csv(path_titanic)

In [ ]:
df

PassengerId  Survived  Pclass  \
0            892         0       3   
1            893         1       3   
2            894         0       2   
3            895         0       3   
4            896         1       3   
..           ...       ...     ...   
413         1305         0       3   
414         1306         1       1   
415         1307         0       3   
416         1308         0       3   
417         1309         0       3   

                                             Name     Sex   Age  SibSp  Parch  \
0                                Kelly, Mr. James    male  34.5      0      0   
1                Wilkes, Mrs. James (Ellen Needs)  female  47.0      1      0   
2                       Myles, Mr. Thomas Francis    male  62.0      0      0   
3                                Wirz, Mr. Albert    male  27.0      0      0   
4    Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female  22.0      1      1   
..                                            ...     ...   ...    ...    ...   
413                            Spector, Mr. Woolf    male   NaN      0      0   
414                  Oliva y Ocana, Dona. Fermina  female  39.0      0      0   
415                  Saether, Mr. Simon Sivertsen    male  38.5      0      0   
416                           Ware, Mr. Frederick    male   NaN      0      0   
417                      Peter, Master. Michael J    male   NaN      1      1   

                 Ticket      Fare Cabin Embarked  
0                330911    7.8292   NaN        Q  
1                363272    7.0000   NaN        S  
2                240276    9.6875   NaN        Q  
3                315154    8.6625   NaN        S  
4               3101298   12.2875   NaN        S  
..                  ...       ...   ...      ...  
413           A.5. 3236    8.0500   NaN        S  
414            PC 17758  108.9000  C105        C  
415  SOTON/O.Q. 3101262    7.2500   NaN        S  
416              359309    8.0500   NaN        S  
417                2668   22.3583   NaN        C  

[418 rows x 12 columns]

In [ ]:
df.shape

(418, 12)

In [ ]:
df.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age             86
SibSp            0
Parch            0
Ticket           0
Fare             1
Cabin          327
Embarked         0
dtype: int64

In [ ]:
df_new =df.drop(columns = ['Cabin','PassengerId','Name','Ticket'])

In [ ]:
df_new.head(162)

Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0           0       3    male  34.5      0      0   7.8292        Q
1           1       3  female  47.0      1      0   7.0000        S
2           0       2    male  62.0      0      0   9.6875        Q
3           0       3    male  27.0      0      0   8.6625        S
4           1       3  female  22.0      1      1  12.2875        S
..        ...     ...     ...   ...    ...    ...      ...      ...
157         1       3  female  23.0      0      0   7.8542        S
158         0       1    male  42.0      0      0  26.5500        S
159         1       3  female  26.0      0      2  13.7750        S
160         1       3  female   NaN      0      0   7.7333        Q
161         0       3    male   7.0      1      1  15.2458        C

[162 rows x 8 columns]

In [ ]:
x = df_new.iloc[:,1:]

In [ ]:
x

Pclass     Sex   Age  SibSp  Parch      Fare Embarked
0         3    male  34.5      0      0    7.8292        Q
1         3  female  47.0      1      0    7.0000        S
2         2    male  62.0      0      0    9.6875        Q
3         3    male  27.0      0      0    8.6625        S
4         3  female  22.0      1      1   12.2875        S
..      ...     ...   ...    ...    ...       ...      ...
413       3    male   NaN      0      0    8.0500        S
414       1  female  39.0      0      0  108.9000        C
415       3    male  38.5      0      0    7.2500        S
416       3    male   NaN      0      0    8.0500        S
417       3    male   NaN      1      1   22.3583        C

[418 rows x 7 columns]

In [ ]:
y = df_new.iloc[:,0]

In [ ]:
y

0      0
1      1
2      0
3      0
4      1
      ..
413    0
414    1
415    0
416    0
417    0
Name: Survived, Length: 418, dtype: int64

In [ ]:
df_new['Parch'].unique()

array([0, 1, 3, 2, 4, 6, 5, 9])

In [ ]:
df_new['SibSp'].unique()

array([0, 1, 2, 3, 4, 5, 8])

In [ ]:
df_new.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Survived  418 non-null    int64  
 1   Pclass    418 non-null    int64  
 2   Sex       418 non-null    object 
 3   Age       332 non-null    float64
 4   SibSp     418 non-null    int64  
 5   Parch     418 non-null    int64  
 6   Fare      417 non-null    float64
 7   Embarked  418 non-null    object 
dtypes: float64(2), int64(4), object(2)
memory usage: 26.2+ KB


In [ ]:
from sklearn.impute import SimpleImputer

In [ ]:
Si = SimpleImputer(strategy = 'mean')

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [ ]:
x_train,x_test,y_train,y_test = train_test_split(x,y, test_size=0.3)

In [ ]:
X_train_age = Si.fit_transform(x_train[['Age','Fare']])
X_test_age = Si.fit_transform(x_test[['Age','Fare']])

In [ ]:
x_train

In [ ]:
X_train_age

array([[1.00000000e+01, 4.69000000e+01],
       [4.50000000e+01, 7.22500000e+00],
       [5.30000000e+01, 2.85000000e+01],
       [2.70000000e+01, 8.66250000e+00],
       [3.00243348e+01, 0.00000000e+00],
       [1.80000000e+01, 3.43750000e+01],
       [2.30000000e+01, 7.05000000e+00],
       [3.90000000e+01, 2.11337500e+02],
       [2.60000000e+01, 2.90000000e+01],
       [3.90000000e+01, 2.97000000e+01],
       [3.00243348e+01, 3.96000000e+01],
       [5.00000000e+01, 1.45000000e+01],
       [5.00000000e+00, 3.13875000e+01],
       [4.00000000e+01, 2.60000000e+01],
       [3.00243348e+01, 7.57500000e+00],
       [2.80000000e+01, 8.05000000e+00],
       [3.70000000e+01, 9.00000000e+01],
       [2.40000000e+01, 6.00000000e+01],
       [3.60000000e+01, 7.52417000e+01],
       [6.70000000e+01, 2.21779200e+02],
       [3.00000000e+01, 1.38583000e+01],
       [3.00000000e+01, 1.55500000e+01],
       [2.20000000e+01, 8.66250000e+00],
       [4.50000000e+01, 3.00000000e+01],
       [2.000000

In [ ]:
X_test_age

array([[ 55.        ,  59.4       ],
       [ 23.        ,  10.5       ],
       [ 25.        ,   7.7958    ],
       [ 29.        ,  22.025     ],
       [ 48.        , 106.425     ],
       [ 18.        ,   7.8792    ],
       [ 27.        ,   7.925     ],
       [ 46.        ,  79.2       ],
       [ 47.        ,  61.175     ],
       [ 32.5       ,   9.5       ],
       [ 26.        ,  13.        ],
       [ 45.        , 262.375     ],
       [ 17.        ,   8.05      ],
       [ 30.85686869,  15.2458    ],
       [ 20.        ,  36.75      ],
       [ 16.        ,   8.5167    ],
       [ 30.85686869,   7.75      ],
       [ 45.        ,  59.4       ],
       [ 18.5       ,   7.2292    ],
       [ 21.        ,  21.        ],
       [ 24.        ,   8.6625    ],
       [ 31.        ,   7.7333    ],
       [ 18.        ,  60.        ],
       [ 18.        ,  10.5       ],
       [ 30.        ,  13.        ],
       [ 30.85686869,  25.4667    ],
       [  0.83      ,   9.35      ],
 

In [ ]:
X_train_age.shape

(292, 2)

In [ ]:
ohe = OneHotEncoder(drop = 'first', sparse_output= False)
X_train_sex = ohe.fit_transform(x_train[['Sex','Embarked']])
X_test_sex = ohe.fit_transform(x_test[['Sex','Embarked']])

In [ ]:
X_train_sex.tolist()

[[0.0, 0.0, 1.0],
 [0.0, 0.0, 0.0],
 [1.0, 0.0, 0.0],
 [1.0, 0.0, 1.0],
 [1.0, 0.0, 1.0],
 [1.0, 0.0, 1.0],
 [1.0, 0.0, 1.0],
 [0.0, 0.0, 1.0],
 [1.0, 0.0, 1.0],
 [1.0, 0.0, 0.0],
 [1.0, 0.0, 1.0],
 [1.0, 0.0, 1.0],
 [1.0, 0.0, 1.0],
 [1.0, 0.0, 1.0],
 [1.0, 0.0, 1.0],
 [1.0, 0.0, 1.0],
 [0.0, 1.0, 0.0],
 [1.0, 0.0, 1.0],
 [1.0, 0.0, 0.0],
 [1.0, 0.0, 1.0],
 [0.0, 0.0, 0.0],
 [0.0, 0.0, 1.0],
 [0.0, 0.0, 1.0],
 [0.0, 0.0, 1.0],
 [1.0, 0.0, 0.0],
 [1.0, 0.0, 1.0],
 [1.0, 0.0, 1.0],
 [1.0, 0.0, 1.0],
 [1.0, 1.0, 0.0],
 [0.0, 0.0, 1.0],
 [1.0, 0.0, 1.0],
 [0.0, 0.0, 1.0],
 [1.0, 0.0, 0.0],
 [1.0, 0.0, 1.0],
 [1.0, 0.0, 1.0],
 [0.0, 1.0, 0.0],
 [0.0, 1.0, 0.0],
 [0.0, 0.0, 0.0],
 [0.0, 1.0, 0.0],
 [1.0, 0.0, 1.0],
 [0.0, 0.0, 0.0],
 [1.0, 0.0, 1.0],
 [1.0, 0.0, 1.0],
 [1.0, 0.0, 1.0],
 [1.0, 0.0, 1.0],
 [1.0, 0.0, 1.0],
 [1.0, 0.0, 1.0],
 [1.0, 0.0, 1.0],
 [1.0, 0.0, 1.0],
 [1.0, 0.0, 1.0],
 [1.0, 1.0, 0.0],
 [1.0, 0.0, 1.0],
 [1.0, 0.0, 1.0],
 [1.0, 0.0, 1.0],
 [1.0, 0.0, 1.0],
 [1.0, 0.0

In [ ]:
x_train

Pclass     Sex    Age  SibSp  Parch     Fare Embarked
140       3  female  10.00      5      2  46.9000        S
19        3  female  45.00      0      0   7.2250        C
131       1    male  53.00      0      0  28.5000        C
363       3    male  27.00      0      0   8.6625        S
266       1    male    NaN      0      0   0.0000        S
..      ...     ...    ...    ...    ...      ...      ...
281       3    male   0.75      1      1  13.7750        S
280       3  female  23.00      0      0   8.6625        S
250       2  female   0.92      1      2  27.7500        S
30        2    male  50.00      1      0  26.0000        S
243       3    male    NaN      0      0   7.8875        S

[292 rows x 7 columns]

In [ ]:
X_train = x_train.drop(columns = ['Sex','Embarked','Age','Fare']).values

X_test= x_test.drop(columns =  ['Sex','Embarked','Age','Fare']).values

In [ ]:
X_train_age__ = x_train.drop(columns = ['Pclass','Sex','SibSp','Parch','Fare','Embarked'])
X_test_age__ = x_test.drop(columns = ['Pclass','Sex','SibSp','Parch','Fare','Embarked'])

In [ ]:
X_train

array([[3, 5, 2],
       [3, 0, 0],
       [1, 0, 0],
       [3, 0, 0],
       [1, 0, 0],
       [3, 2, 2],
       [3, 0, 0],
       [1, 0, 0],
       [2, 1, 1],
       [1, 0, 0],
       [1, 0, 0],
       [3, 1, 0],
       [3, 4, 2],
       [2, 1, 0],
       [3, 0, 0],
       [3, 0, 0],
       [1, 1, 0],
       [1, 1, 0],
       [1, 0, 0],
       [1, 1, 0],
       [2, 1, 0],
       [3, 1, 0],
       [3, 2, 0],
       [2, 0, 2],
       [2, 0, 0],
       [3, 0, 0],
       [2, 1, 1],
       [3, 0, 0],
       [3, 0, 0],
       [2, 1, 2],
       [3, 0, 0],
       [3, 0, 0],
       [3, 0, 0],
       [3, 0, 0],
       [2, 0, 0],
       [3, 0, 0],
       [3, 0, 0],
       [3, 1, 1],
       [3, 0, 0],
       [3, 0, 0],
       [1, 0, 1],
       [3, 0, 0],
       [2, 0, 0],
       [2, 1, 0],
       [3, 0, 0],
       [3, 1, 5],
       [3, 0, 0],
       [2, 1, 0],
       [1, 0, 0],
       [3, 0, 0],
       [3, 0, 0],
       [3, 0, 0],
       [2, 0, 0],
       [2, 0, 0],
       [2, 0, 0],
       [3,

In [ ]:
X_train_transformed = np.concatenate((X_train,X_train_age,X_train_sex),axis=1)
X_test_transformed = np.concatenate((X_test,X_test_age,X_test_sex),axis=1)

In [ ]:
df_g =X_train_transformed.tolist()

In [ ]:
df_g

[[3.0, 5.0, 2.0, 10.0, 46.9, 0.0, 0.0, 1.0],
 [3.0, 0.0, 0.0, 45.0, 7.225, 0.0, 0.0, 0.0],
 [1.0, 0.0, 0.0, 53.0, 28.5, 1.0, 0.0, 0.0],
 [3.0, 0.0, 0.0, 27.0, 8.6625, 1.0, 0.0, 1.0],
 [1.0, 0.0, 0.0, 30.0243347639485, 0.0, 1.0, 0.0, 1.0],
 [3.0, 2.0, 2.0, 18.0, 34.375, 1.0, 0.0, 1.0],
 [3.0, 0.0, 0.0, 23.0, 7.05, 1.0, 0.0, 1.0],
 [1.0, 0.0, 0.0, 39.0, 211.3375, 0.0, 0.0, 1.0],
 [2.0, 1.0, 1.0, 26.0, 29.0, 1.0, 0.0, 1.0],
 [1.0, 0.0, 0.0, 39.0, 29.7, 1.0, 0.0, 0.0],
 [1.0, 0.0, 0.0, 30.0243347639485, 39.6, 1.0, 0.0, 1.0],
 [3.0, 1.0, 0.0, 50.0, 14.5, 1.0, 0.0, 1.0],
 [3.0, 4.0, 2.0, 5.0, 31.3875, 1.0, 0.0, 1.0],
 [2.0, 1.0, 0.0, 40.0, 26.0, 1.0, 0.0, 1.0],
 [3.0, 0.0, 0.0, 30.0243347639485, 7.575, 1.0, 0.0, 1.0],
 [3.0, 0.0, 0.0, 28.0, 8.05, 1.0, 0.0, 1.0],
 [1.0, 1.0, 0.0, 37.0, 90.0, 0.0, 1.0, 0.0],
 [1.0, 1.0, 0.0, 24.0, 60.0, 1.0, 0.0, 1.0],
 [1.0, 0.0, 0.0, 36.0, 75.2417, 1.0, 0.0, 0.0],
 [1.0, 1.0, 0.0, 67.0, 221.7792, 1.0, 0.0, 1.0],
 [2.0, 1.0, 0.0, 30.0, 13.8583, 0.0, 0.0, 0.0]

In [ ]:
X_train_transformed.shape

(292, 8)

In [ ]:
model = LogisticRegression()

In [ ]:
y_test.shape

(126,)

In [ ]:
print(x.shape,X_train_transformed.shape,X_test_transformed.shape)

(418, 7) (292, 8) (126, 8)


In [ ]:
model.fit(X_train_transformed,y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [ ]:
print(y_test)

20     0
406    0
95     0
394    0
239    1
      ..
224    1
139    0
272    1
330    1
72     1
Name: Survived, Length: 126, dtype: int64


In [ ]:
X_train_prediction = model.predict(X_train_transformed)

In [ ]:
print(X_train_prediction)

[1 1 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 0 0 0 1 1 1 1 0 0 0 0 0 1 0 1 0 0 0 1 1
 1 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 1 1 0 1 0 0 1 0 0 0 1 0
 1 0 0 0 0 0 1 0 1 0 0 0 1 0 0 0 0 0 1 0 0 0 1 0 0 0 0 1 0 0 1 0 1 1 0 1 0
 1 1 1 0 1 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 1 1 0 1 0 1 0 0 1 1 0 1 0 1 1 0 0
 1 0 0 0 0 0 1 1 0 0 0 1 0 1 0 0 1 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 1 0
 1 1 0 1 0 0 0 1 0 0 0 0 1 0 1 0 1 0 1 0 1 0 1 0 0 1 1 0 1 0 1 0 0 0 1 0 0
 1 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0 0 1 1 0 1 0 1 0 1 0 0 1 1 1 1
 0 0 0 0 0 1 0 0 1 0 1 1 0 1 0 0 0 1 0 0 0 0 0 0 1 0 1 0 0 1 1 0 0]


In [ ]:
training_data_accuracy = accuracy_score(y_train,X_train_prediction)
print('accuracy', training_data_accuracy)

accuracy 1.0


In [ ]:
y_pred = model.predict(X_test_transformed)

In [ ]:
print(y_pred)

[0 0 0 0 1 1 1 0 1 0 0 1 0 1 1 1 1 1 0 1 0 0 1 0 1 1 0 1 0 0 0 1 0 0 1 1 1
 0 0 1 1 0 1 1 0 1 0 0 1 1 0 0 1 1 0 1 0 0 1 0 0 0 0 1 1 0 1 0 0 0 1 0 0 0
 0 0 0 1 1 1 0 0 0 0 1 0 1 1 1 1 0 0 0 0 0 1 0 0 0 0 1 0 1 0 1 1 0 1 1 0 1
 0 0 1 0 0 0 0 0 0 0 1 0 1 1 1]


In [ ]:
acc = accuracy_score(y_pred,y_test)

In [ ]:
acc

1.0